// Sleep UI: add/edit/delete sleep records
(function(){
  const $=s=>document.querySelector(s);
  const sheet='Sleep';
  function today(){ return (new Date()).toISOString().slice(0,10); }
  async function loadSleep(){ $('#sleep-list').innerHTML='Loading...'; try{ const res = await Api.getSheet(sheet); const rows = res.data||[]; rows.sort((a,b)=> new Date(b.Date)-new Date(a.Date)); if(!rows.length){ $('#sleep-list').innerHTML='<div class="card">No sleep records</div>'; return; } const container=document.createElement('div'); rows.forEach(r=>{ const el=document.createElement('div'); el.className='card'; el.innerHTML=`<div style='display:flex;justify-content:space-between'><div>${r.Date}<div style='color:var(--muted)'>${Math.round((Number(r.Minutes)||0)/60)}h ${(Number(r.Minutes)||0)%60}m • ${r.Quality||''}</div></div><div><button class='btn small edit-sl' data-id='${r.ID}'>Edit</button> <button class='btn small del-sl' data-id='${r.ID}'>Delete</button></div></div>`; container.appendChild(el); }); $('#sleep-list').innerHTML=''; $('#sleep-list').appendChild(container); Array.from(document.querySelectorAll('.edit-sl')).forEach(b=>b.addEventListener('click', onEdit)); Array.from(document.querySelectorAll('.del-sl')).forEach(b=>b.addEventListener('click', onDelete)); }catch(e){console.error(e); $('#sleep-list').innerHTML='Failed to load'; } }
  function reset(){ $('#sleep-date').value=''; $('#sleep-minutes').value=''; $('#sleep-quality').value='Good'; $('#sleep-notes').value=''; }
  async function onSave(ev){ ev.preventDefault(); const payload={ Date: $('#sleep-date').value||today(), Minutes: Number($('#sleep-minutes').value)||0, Quality: $('#sleep-quality').value, Notes: $('#sleep-notes').value }; try{ await Api.addSleep(payload); showToast('Saved'); reset(); await loadSleep(); await window.loadDashboard && window.loadDashboard(); }catch(e){console.error(e); showToast('Failed');} }
  async function onEdit(ev){ const id=ev.currentTarget.dataset.id; const res = await Api.getSheet(sheet); const item=(res.data||[]).find(x=>String(x.ID)===String(id)); if(!item) return; $('#sleep-date').value=item.Date; $('#sleep-minutes').value=item.Minutes; $('#sleep-quality').value=item.Quality||'Good'; $('#sleep-notes').value=item.Notes||''; }
  async function onDelete(ev){ if(!confirm('Delete sleep record?')) return; const id=ev.currentTarget.dataset.id; try{ await Api.deleteSleep(id); showToast('Deleted'); await loadSleep(); await window.loadDashboard && window.loadDashboard(); }catch(e){console.error(e); showToast('Failed');} }
  document.addEventListener('DOMContentLoaded', ()=>{ document.getElementById('sleep-form').addEventListener('submit', onSave); loadSleep(); });
})();